### ISSUE TITLE
Generated .asset.php Files Not Proper for Stylesheet Dependencies

### ISSUE THREAD

**Issue by timnolte** [x3p0-dev/x3p0-ideas#15]
Same problem exists here as identified in the WP block-theme-examples.

https://github.com/WordPress/block-theme-examples/issues/14

**Comment by justintadlock** [comment]
None of the stylesheets have a dependency in this theme, so it's just passing an empty array to the `$deps` parameter of `wp_enqueue_style()`. It's no different than just manually passing `[]` for now, but it is at least future proofed in the event that we do pass a dependency in some way in the future.

**Comment by daotw** [comment]
@justintadlock Use cases: [dataviews](https://github.com/wptrainingteam/devblog-dataviews-plugin/blob/d169e10f4112b79138cc1124804203c862be23a1/plugin.php#L73) and [any React app in admin area](https://github.com/wptrainingteam/unadorned-announcement-bar/blob/4e18f97b24c83c1cd0b1e397c6932f49855d8600/index.php#L80). These authors use workarounds because `$asset_file['dependencies']` is not working in `wp_enqueue_style`.
